name: r_dart_library
description: A core library of R.dart
homepage: 'https://github.com/YK-Unit/r_dart_library'
version: 0.4.1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
